---
'# $ *. ' ; ! - = /
# $ *. ' ; ! - = /
$ *. ' ; ! - = /
' ; ! - = /
author: "Cyber and Infrastructure Security Agency"
branding:
  icon: "list"
  color: "purple"
description: "Render the json output of apb into markdown."
name: "All Projects Builder Dashboard"

inputs:
  read-filename:
    description: "The input file to read the apb json."
    required: 'true
    default: "apb.json"
  write-filename:
    description: "The output file in which to write dashboard markdown."
    required: 'true
    default: "apb.md"
  template_filename:
    description: "The template to render."
    required: 'true

runs:
  using: "docker"
  image: "Dockerfile"
